INSERT INTO users VALUES (NULL, 500.0, 'password', 'smithy12'),(NULL, 500.0, 'pass', 'user'),(NULL, 100.0, 'password', 'murph12'),(NULL, 1000.0, 'password', 'jonesy12'),(NULL, 400.0, 'password', 'damo12');
INSERT INTO users VALUES (NULL, 500.0, 'password', 'mick12');
INSERT INTO users VALUES (NULL, 500.0, 'password', 'col12');
INSERT INTO users VALUES (NULL, 500.0, 'password', 'kev12');


INSERT INTO projects VALUES (NULL, timestamp'2016-09-09 09:30:25 GMT', '2016-12-15','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam pharetra sit amet diam ut venenatis. Duis ullamcorper lectus ut neque maximus, tristique cursus arcu ullamcorper. Vivamus condimentum nisi a mauris pellentesque fringilla. Nunc in lectus id nunc finibus fringilla. Donec a aliquam eros. In aliquam augue vel viverra viverra. Cras ullamcorper turpis enim, nec malesuada est luctus non. Vivamus a augue mi.', 1200.00, '../images/money_tree.jpg', 'Money Tree', 1);
INSERT INTO projects VALUES (NULL, timestamp'2016-10-10 09:30:25 GMT', '2016-12-25','Quisque blandit elementum mi, faucibus vehicula magna aliquet ut. Vivamus ac dui auctor, tincidunt sem et, pellentesque risus. Donec cursus est sit amet est interdum hendrerit. Nunc gravida tincidunt purus eu facilisis. Aenean varius id odio et maximus. Proin suscipit magna id nunc porttitor, ac pharetra erat ornare. Nulla pretium felis tincidunt, condimentum mi vitae, congue mi. Donec tempus placerat orci in viverra. Quisque eget velit pretium, pellentesque enim in, sollicitudin ipsum. Quisque iaculis, lorem rhoncus rutrum ultrices, dui eros luctus sapien, eu rutrum justo mauris quis mauris. Duis nec massa ullamcorper, semper turpis non, placerat magna. Nulla consectetur leo libero, sit amet tempus libero vulputate non.', 1249.00, '../images/cats_eyes.png', 'Cat Contact Lenses', 2);
INSERT INTO projects VALUES (NULL, timestamp'2016-11-11 09:30:25 GMT', '2016-12-31','Cras odio quam, cursus ac pretium vel, consectetur eu sapien. Mauris id orci vehicula, laoreet felis non, laoreet tortor. Mauris lorem metus, molestie ac molestie aliquet, tempus in ipsum. Suspendisse viverra facilisis orci, malesuada aliquam enim hendrerit vel. Mauris laoreet mattis leo in sodales. Nullam nec sem nec libero hendrerit ornare in at orci. Maecenas porttitor odio vitae posuere sollicitudin. Nulla facilisi. Donec consectetur pretium risus at eleifend. Aenean bibendum turpis vel interdum placerat. Morbi euismod semper mi, vitae tempus dui posuere eu. Nullam tortor turpis, iaculis sagittis gravida eu, vulputate ac quam.', 3000.00, '../images/tea_bags.jpg', 'Washable Teabags', 3);
INSERT INTO projects VALUES (NULL, timestamp'2016-12-1 09:30:25 GMT', '2017-02-01','Nulla bibendum enim non felis feugiat, a pulvinar est convallis. Cras luctus vestibulum lectus, a sagittis dui tincidunt et. Nulla congue elit at lorem finibus gravida. Donec risus orci, feugiat sit amet mi vitae, venenatis interdum mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris aliquet ultricies mi id tincidunt. Pellentesque lacinia nulla vel tempor mattis. Vestibulum blandit neque vel pellentesque auctor. Maecenas tincidunt nisi a erat pretium fermentum. Donec id ante tempor, consectetur tortor sed, placerat libero. Vivamus nulla mauris, eleifend sed est nec, porttitor blandit diam. Nullam risus diam, efficitur non ullamcorper non, gravida at purus. Sed blandit lacus a tellus sodales porttitor. Mauris tempor posuere porta.', 6000.00, '../images/toliet_tissue.jpg', 'Re-usable Toilet Paper', 4);

INSERT INTO projects VALUES (NULL, timestamp'2016-12-02 09:30:25 GMT', '2017-02-02','Mauris quis odio augue. Integer convallis dictum tortor, sed venenatis ligula dignissim id. Pellentesque at lacus porta dui efficitur viverra sed in erat. Nam maximus nisi vel lacus pharetra auctor. Curabitur varius arcu dui, at euismod velit posuere eget. Nulla a quam ut mi interdum lacinia at a ex. Sed at purus a lectus volutpat scelerisque vitae vitae elit. Sed lacinia vel ante a suscipit. Curabitur at enim pharetra, fermentum nisl hendrerit, egestas est. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque sit amet dolor vel nisi bibendum dapibus non a urna. Quisque leo libero, blandit sed dui sed, ultricies pharetra turpis. Vivamus dolor libero, dictum vitae lacus a, pretium vehicula turpis. In sem erat, aliquet vel orci vel, fringilla ornare mi.', 2200.00, '../images/drink-dispenser.jpg', 'Drink Dispenser', 4);
INSERT INTO projects VALUES (NULL, timestamp'2016-12-02 09:30:25 GMT', '2017-02-02','Vivamus faucibus, erat vel semper ullamcorper, nisl velit fermentum libero, at ullamcorper nisi risus finibus urna. Ut tincidunt eu neque id lobortis. Integer vitae malesuada est, id congue sem. Aliquam ut imperdiet felis. Morbi ultrices nibh vitae luctus euismod. Sed congue elit et purus tempus lobortis. Proin et mollis massa. Aliquam egestas, velit vitae mollis porttitor, lacus magna suscipit augue, non lacinia augue urna ac arcu. Sed sit amet elit eu nunc fringilla sagittis. Maecenas velit orci, porta id odio non, gravida egestas orci. Donec rutrum vehicula libero, vulputate molestie justo faucibus ac. ', 3200.00, '../images/pet-rock.jpg', 'Caring for Pet Rocks Book', 3);
INSERT INTO projects VALUES (NULL, timestamp'2016-12-02 09:30:25 GMT', '2017-02-02','Suspendisse molestie interdum neque, vitae rhoncus ante tincidunt quis. Mauris ullamcorper tincidunt tempor. Sed vitae finibus lacus. Nulla pellentesque tellus in tellus aliquet ullamcorper. Sed hendrerit tincidunt lacus non facilisis. Vivamus scelerisque malesuada consectetur. Nulla mollis dui sed ipsum tempor, vel posuere enim pharetra. Aenean nec semper mi, in molestie velit. Quisque in elementum est, non gravida justo. Curabitur lacus nunc, consequat eget lacinia vel, luctus vitae turpis. Quisque porttitor ultricies augue, sit amet sollicitudin dui elementum ut.', 1000.00, '../images/tea-potty.jpg', 'Tea Potty', 3);
INSERT INTO projects VALUES (NULL, timestamp'2016-12-02 09:30:25 GMT', '2017-02-02','Nulla facilisi. Maecenas rhoncus posuere ultrices. Vivamus congue non nibh ac rhoncus. Pellentesque at eleifend lacus, ut mollis est. Suspendisse in pharetra lacus, vehicula efficitur risus. Aenean fringilla nec leo in interdum. Nunc fermentum nunc tincidunt arcu elementum sagittis nec et mauris. Fusce eu felis quis quam sagittis condimentum non sed arcu. Ut euismod maximus libero a porta. Maecenas in varius ante, ac auctor quam. Suspendisse elementum dui a quam finibus, ac volutpat leo eleifend. Aenean eu lacus nibh. Proin scelerisque at sem bibendum accumsan.', 16000.00, '../images/teddy-usb.jpg', 'Teddy Bear Memory Stick', 4);


INSERT INTO pledges VALUES (NULL, 15.0, timestamp'2016-10-29 09:30:25 GMT', 2, 4), (NULL, 120.0, timestamp'2016-11-09 09:30:25 GMT', 1, 2), (NULL, 75.0, timestamp'2016-10-30 09:30:25 GMT', 4, 2);
INSERT INTO pledges VALUES (NULL, 25.0, timestamp'2016-12-01 09:30:25 GMT', 2, 3), (NULL, 20.0, timestamp'2016-12-01 09:30:25 GMT', 1, 3), (NULL, 50.0, timestamp'2016-12-01 09:30:25 GMT', 4, 3);

INSERT INTO pledges VALUES (NULL, 20.0, timestamp'2016-12-03 09:30:25 GMT', 5, 5);
INSERT INTO pledges VALUES (NULL, 50.0, timestamp'2016-12-03 09:30:25 GMT', 6, 6);
INSERT INTO pledges VALUES (NULL, 40.0, timestamp'2016-12-03 09:30:25 GMT', 6, 7);
INSERT INTO pledges VALUES (NULL, 70.0, timestamp'2016-12-03 09:30:25 GMT', 7, 6);